mvcbd/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcbd.Models;


namespace mvcbd.Controllers
{
    public class CargoController : Controller
    {
        //
        // GET: /Cargo/

        bd_escuelaEntities entidad = new bd_escuelaEntities();


        public ActionResult Index()
        {
            var listacargos = entidad.cargo;

            return View(listacargos.ToList());
        }

        public ActionResult ListadoMaestraCargos()
        {
            var listacargos = entidad.cargo;
            return View(listacargos.ToList());

        }

        public ActionResult UsuarioxCargo(string cargo)
        {
            var modelo = from p in entidad.usuario where p.cargo.car_des == cargo select p;
            return View(modelo.ToList());

        }

        public ActionResult ListadoUsuarioconDescripcionCargo()
        {
            var modelo= from p in entidad.usuario 
                        join c in entidad.cargo
                        on p.car_cod equals c.car_cog
                                                  select new ElUsuario
                                                  {
                                                    codigo=p.usu_cod,
                                                    nombre=p.usu_nom,
                                                    cargo=c.car_des
                                                  };
            return View(modelo.ToList());

        }

    }
}

mvcbd/Controllers/CrudUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcbd.Models;

namespace mvcbd.Controllers
{
    public class CrudUsuarioController : Controller
    {
        private bd_escuelaEntities db = new bd_escuelaEntities();

        //
        // GET: /CrudUsuario/

        public ActionResult Index()
        {
            var usuario = db.usuario.Include(u => u.cargo);
            return View(usuario.ToList());
        }

        //
        // GET: /CrudUsuario/Details/5

        public ActionResult Details(int id = 0)
        {
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        //
        // GET: /CrudUsuario/Create

        public ActionResult Create()
        {
            ViewBag.car_cod = new SelectList(db.cargo, "car_cog", "car_des");
            return View();
        }

        //
        // POST: /CrudUsuario/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.car_cod = new SelectList(db.cargo, "car_cog", "car_des", usuario.car_cod);
            return View(usuario);
        }

        //
        // GET: /CrudUsuario/Edit/5

        public ActionResult Edit(int id = 0)
        {
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.car_cod = new SelectList(db.cargo, "car_cog", "car_des", usuario.car_cod);
            return View(usuario);
        }

        //
        // POST: /CrudUsuario/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.car_cod = new SelectList(db.cargo, "car_cog", "car_des", usuario.car_cod);
            return View(usuario);
        }

        //
        // GET: /CrudUsuario/Delete/5

        public ActionResult Delete(int id = 0)
        {
            usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        //
        // POST: /CrudUsuario/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            usuario usuario = db.usuario.Find(id);
            db.usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

mvcbd/Controllers/MantenimientoCargosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvcbd.Models;

namespace mvcbd.Controllers
{
    public class MantenimientoCargosController : Controller
    {
        private bd_escuelaEntities db = new bd_escuelaEntities();

        //
        // GET: /MantenimientoCargos/

        public ActionResult Index()
        {
            return View(db.cargo.ToList());
        }

        //
        // GET: /MantenimientoCargos/Details/5

        public ActionResult Details(int id = 0)
        {
            cargo cargo = db.cargo.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // GET: /MantenimientoCargos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MantenimientoCargos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(cargo cargo)
        {
            if (ModelState.IsValid)
            {
                db.cargo.Add(cargo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cargo);
        }

        //
        // GET: /MantenimientoCargos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            cargo cargo = db.cargo.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // POST: /MantenimientoCargos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(cargo cargo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cargo);
        }

        //
        // GET: /MantenimientoCargos/Delete/5

        public ActionResult Delete(int id = 0)
        {
            cargo cargo = db.cargo.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // POST: /MantenimientoCargos/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cargo cargo = db.cargo.Find(id);
            db.cargo.Remove(cargo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

mvcbd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mi aplicación ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("su logotipo aquí", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                            <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                            <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Listado de cargos", "Index", "Cargo")</li>
                            <li>@Html.ActionLink("Maestro Listado", "ListadoMaestraCargos", "Cargo")</li>
                            <li>@Html.ActionLink("Usuarios con cargo", "ListadoUsuarioconDescripcionCargo", "Cargo")</li>
                            <li>@Html.ActionLink("Mantenimiento", "Index", "MantenimientoCargos")</li>
                            <li>@Html.ActionLink("Usuarios CRUD", "Index", "CrudUsuario")</li>

                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>